# Generated by Django 2.1.2 on 2018-10-06 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import housing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField(help_text='The start date of the tournament.', verbose_name='end date')),
                ('date_start', models.DateField(help_text='The end date of the tournament.', verbose_name='start date')),
                ('description', models.TextField(blank=True, default='', help_text='Additional information about the tournament.')),
                ('location', models.CharField(help_text='The location where the tournament is ocurring.', max_length=255, verbose_name='location')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('slug_key', models.CharField(db_index=True, default=housing.models.generate_slug_key, editable=False, help_text='A unique key to improve uniqueness of the slug.', max_length=6, verbose_name='slug key')),
                ('user', models.ForeignKey(help_text='The user who registered the tournament.', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', related_query_name='tournament', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tournament',
                'verbose_name_plural': 'tournaments',
                'ordering': ('date_start', 'name'),
            },
        ),
    ]
