# Generated by Django 2.1.2 on 2018-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_end',
            field=models.DateField(help_text='The end date of the tournament.', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateField(help_text='The start date of the tournament.', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(help_text='The location where the tournament is occurring.', max_length=255, verbose_name='location'),
        ),
    ]
