# Generated by Django 2.1.2 on 2018-10-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_tournament-typos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_lockout',
            field=models.DateTimeField(help_text='The date and time to freeze host and team registrations at. This may not be edited.', verbose_name='registration lockout date'),
        ),
    ]
