# Generated by Django 2.1.2 on 2018-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_hostteammatch_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='email',
            field=models.EmailField(default='', help_text='An email address to contact the host.', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(default='', help_text='A phone number to contact the host.', max_length=30, verbose_name='phone number'),
        ),
    ]
