# Generated by Django 2.1.2 on 2018-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_auto_20181007_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_matched',
            field=models.BooleanField(default=False, help_text='A boolean indicating if matching has been run yet.', verbose_name='is matched'),
        ),
    ]
